### ISSUE TITLE
This plugin is not working with Q2A 1.7.1

### ISSUE THREAD

**Issue by gurjyot** [q2apro/q2apro-comment-to-answer#2]
I uploaded the plugin and it is showing in plugin section but without any option to enable it or so. That's why I thought it might be working straight on without any need to enable it. 
But when I edit an comment it doesn't show any option for changing comment to answer.

http://question2answer.org/qa/48091

**Comment by phy25** [comment]
How to use this plugin: Go to /convertcomment, for example, if your q2a is at http://example.com/q2a/, then navigate to http://example.com/q2a/convertcomment .

**Comment by gurjyot** [comment]
Thanks a lot @phy25 Your comment worked like charm.
It was my stupidity that it didn't worked in the first go because I forgot to read the readme file of this plugin.
But thanks again... :)
